version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    build: postgres
    container_name: pg-container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trainingsDB
    ports:
      - '5432:5432'